import { describe, expect, test } from "bun:test";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { parseCli } from "../framework/cli/parse-args.ts";
import { loadEnvFile, parseEnvFile } from "../framework/cli/env.ts";
import { generateServerlessYaml } from "../framework/cli/serverless.ts";
import { createRouter, defineConfig, query } from "../framework/index.ts";
import { z } from "zod";

const FIXTURE_APP = join(import.meta.dir, "fixtures/example-app");
const OVENLESS_ROOT = join(FIXTURE_APP, "../../..");

function createBuildFixture(): string {
  if (!existsSync(join(OVENLESS_ROOT, "dist/index.js"))) {
    throw new Error("Missing dist/index.js — run `bun run build` in the ovenless package first");
  }

  const dir = mkdtempSync(join(tmpdir(), "ovenless-build-"));
  cpSync(join(FIXTURE_APP, "src"), join(dir, "src"), { recursive: true });
  cpSync(join(FIXTURE_APP, "ovenless.config.ts"), join(dir, "ovenless.config.ts"));
  writeFileSync(
    join(dir, "package.json"),
    JSON.stringify(
      {
        name: "ovenless-fixture-app",
        private: true,
        type: "module",
        dependencies: { zod: "^4.4.3" },
      },
      null,
      2,
    ),
  );

  mkdirSync(join(dir, "node_modules"), { recursive: true });
  symlinkSync(OVENLESS_ROOT, join(dir, "node_modules", "ovenless"), "junction");

  const install = Bun.spawnSync(["bun", "install"], {
    cwd: dir,
    stdout: "inherit",
    stderr: "inherit",
  });

  if (install.exitCode !== 0) {
    throw new Error("Failed to install fixture dependencies");
  }

  return dir;
}

describe("CLI parse-args", () => {
  test("parses start --watch", () => {
    const parsed = parseCli(["bun", "ovenless", "start", "--watch"]);
    expect(parsed.command).toBe("start");
    expect(parsed.flags.watch).toBe(true);
    expect(parsed.flags.profile).toBe("development");
  });

  test("parses build --profile staging", () => {
    const parsed = parseCli(["bun", "ovenless", "build", "--profile", "staging"]);
    expect(parsed.command).toBe("build");
    expect(parsed.flags.profile).toBe("staging");
  });

  test("defaults build profile to production", () => {
    const parsed = parseCli(["bun", "ovenless", "build"]);
    expect(parsed.flags.profile).toBe("production");
  });
});

describe("CLI env loading", () => {
  test("parses env files", () => {
    const parsed = parseEnvFile(`
      # comment
      PORT=3000
      NAME="Ovenless"
    `);
    expect(parsed).toEqual({ PORT: "3000", NAME: "Ovenless" });
  });

  test("loads profile env in order", () => {
    const dir = mkdtempSync(join(tmpdir(), "ovenless-env-"));
    writeFileSync(join(dir, ".env"), "SHARED=1\nAPP_ENV=base\n");
    writeFileSync(join(dir, ".env.staging"), "APP_ENV=staging\nSTAGE_ONLY=yes\n");

    const prev = { ...process.env };
    try {
      loadEnvFile(join(dir, ".env"));
      loadEnvFile(join(dir, ".env.staging"), true);
      expect(process.env.SHARED).toBe("1");
      expect(process.env.APP_ENV).toBe("staging");
      expect(process.env.STAGE_ONLY).toBe("yes");
    } finally {
      process.env = prev;
    }

    rmSync(dir, { recursive: true, force: true });
  });
});

describe("CLI serverless generation", () => {
  test("generates serverless.yml content", () => {
    const router = createRouter({
      ping: query({
        input: z.object({}),
        output: z.object({ ok: z.boolean() }),
        handler: () => ({ ok: true }),
      }),
    });

    const config = defineConfig({
      router,
      service: "demo-api",
      title: "Demo",
      version: "1.0.0",
      aws: { region: "eu-west-1", runtime: "nodejs20.x" },
    });

    const yaml = generateServerlessYaml(config, "staging", {
      APP_ENV: "staging",
      API_KEY: "secret",
    });

    expect(yaml).toContain("service: demo-api");
    expect(yaml).toContain("region: eu-west-1");
    expect(yaml).toContain("stage: staging");
    expect(yaml).toContain("APP_ENV: staging");
    expect(yaml).toContain("handler: dist/handler.awsHandler");
    expect(yaml).toContain("Generated by Ovenless");
  });
});

describe("CLI build", () => {
  test("builds lambda bundle and serverless.yml from fixture app", async () => {
    const dir = createBuildFixture();

    try {
      const { runBuild } = await import("../framework/cli/build.ts");
      await runBuild("development", dir);

      expect(existsSync(join(dir, "dist/handler.js"))).toBe(true);
      expect(readFileSync(join(dir, "dist/handler.js"), "utf8")).toContain("awsHandler");
      expect(readFileSync(join(dir, "serverless.yml"), "utf8")).toContain("ovenless-fixture");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
