import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { type OvenlessConfig, type OvenlessProfile, resolveProfileStage } from "../config.ts";

function yamlString(value: string): string {
  if (/^[A-Za-z0-9_./-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function renderEnvironment(env: Record<string, string>): string {
  const entries = Object.entries(env).filter(([key]) => key !== "OVENLESS_PROFILE");
  if (entries.length === 0) return "";

  const lines = entries.map(([key, value]) => `    ${key}: ${yamlString(value)}`);
  return `\n  environment:\n${lines.join("\n")}`;
}

export function generateServerlessYaml(
  config: OvenlessConfig,
  profile: OvenlessProfile,
  env: Record<string, string>,
): string {
  const region = config.aws?.region ?? env.AWS_REGION ?? "us-east-1";
  const runtime = config.aws?.runtime ?? "nodejs20.x";
  const stage = config.aws?.stage ?? resolveProfileStage(profile);

  return `# Generated by Ovenless — profile: ${profile}
# Re-run: ovenless build --profile ${profile}

service: ${config.service}

frameworkVersion: "3"

provider:
  name: aws
  runtime: ${runtime}
  region: ${region}
  stage: ${stage}${renderEnvironment(env)}

functions:
  api:
    handler: dist/handler.awsHandler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY

package:
  individually: true
  patterns:
    - "!**"
    - "dist/**"
`;
}

export function writeServerlessYaml(
  config: OvenlessConfig,
  profile: OvenlessProfile,
  env: Record<string, string>,
  root = process.cwd(),
): string {
  const content = generateServerlessYaml(config, profile, env);
  const path = join(root, "serverless.yml");
  writeFileSync(path, content, "utf8");
  return path;
}
