import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { type OvenlessConfig, type OvenlessProfile, resolveProfileStage } from "../config.ts";
import { getRouterAuth } from "../core.ts";

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function renderEnvironment(env: Record<string, string>): string {
  const entries = Object.entries(env).filter(([key]) => key !== "OVENLESS_PROFILE");
  if (entries.length === 0) return "";

  const lines = entries.map(([key, value]) => `    ${key}: ${yamlString(value)}`);
  return `\n  environment:\n${lines.join("\n")}`;
}

function renderHttpApiAuthorizer(): string {
  return `
  httpApi:
    authorizers:
      ovenlessJwt:
        type: request
        functionName: authorizer
        identitySource:
          - $request.header.Authorization
          - $request.header.Cookie
`;
}

function renderAuthorizerFunction(): string {
  return `
  authorizer:
    handler: dist/authorizer.jwtAuthorizer
    timeout: 10
`;
}

function renderApiEvents(useAuthorizer: boolean): string {
  const authBlock = useAuthorizer
    ? `
          authorizer:
            name: ovenlessJwt
`
    : "";

  return `    events:
      - httpApi:
          path: /{proxy+}
          method: ANY${authBlock}
      - httpApi:
          path: /
          method: ANY${authBlock}
`;
}

export function generateServerlessYaml(
  config: OvenlessConfig,
  profile: OvenlessProfile,
  env: Record<string, string>,
): string {
  const region = config.aws?.region ?? env.AWS_REGION ?? "us-east-1";
  const runtime = config.aws?.runtime ?? "nodejs20.x";
  const stage = config.aws?.stage ?? resolveProfileStage(profile);
  const routerAuth = getRouterAuth(config.router);
  const useAuthorizer = routerAuth?.authorizer === true;

  const packagePatterns = useAuthorizer
    ? `    - "!**"
    - "dist/**"
    - "cert/${profile}/**"`
    : `    - "!**"
    - "dist/**"`;

  return `# Generated by Ovenless — profile: ${profile}
# Re-run: ovenless build --profile ${profile}

service: ${config.service}

frameworkVersion: "3"

provider:
  name: aws
  runtime: ${runtime}
  region: ${region}
  stage: ${stage}${renderEnvironment(env)}${useAuthorizer ? renderHttpApiAuthorizer() : ""}

functions:${useAuthorizer ? renderAuthorizerFunction() : ""}
  api:
    handler: dist/handler.awsHandler
${renderApiEvents(useAuthorizer)}
package:
  individually: true
  patterns:
${packagePatterns}
`;
}

export function writeServerlessYaml(
  config: OvenlessConfig,
  profile: OvenlessProfile,
  env: Record<string, string>,
  root = process.cwd(),
): string {
  const content = generateServerlessYaml(config, profile, env);
  const path = join(root, "serverless.yml");
  writeFileSync(path, content, "utf8");
  return path;
}
